const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const out=path.resolve(__dirname,'../qa-evidence');
fs.mkdirSync(out,{recursive:true});
(async()=>{
  let b=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  let p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];
  p.on('pageerror',e=>errors.push(e.message));
  await p.goto(require('url').pathToFileURL(path.resolve(__dirname,'../static/security.html')).href);
  await p.evaluate(()=>localStorage.removeItem('mandate-security-v1'));
  await p.reload();
  const login=await p.locator('#entry').innerText();
  if(!/not authentication/i.test(login)) throw Error('Login must state demo is not authentication');
  if(!/Yari/i.test(login)||!/inspect-only/i.test(login)) throw Error('Login must present Yari and auditor personas');
  await p.getByRole('button',{name:'Enter workspace'}).click();
  await p.screenshot({path:path.join(out,'security-overview.png'),fullPage:true});
  const overview=await p.locator('#content').innerText();
  if(!/coverage/i.test(overview)) throw Error('Overview must describe coverage counts');
  if(!/not live telemetry/i.test(overview)) throw Error('Evidence flow must stay labeled as illustration');
  await p.getByRole('button',{name:'Investigate with the analyst'}).click();
  await p.locator('#message').fill('Why does MFA conflict?');
  await p.locator('#chatForm button').click();
  const promptBubble=await p.locator('#chatlog .bubble.user').last().innerText();
  if(/employee assertion/i.test(promptBubble)) throw Error('Investigation prompt labeled as employee assertion');
  await p.locator('#message').fill('When was the last restore?');
  await p.locator('#chatForm button').click();
  const restoreChat=await p.locator('#chatlog').innerText();
  if(/AWS RDS/i.test(restoreChat)) throw Error('restore mapped to storage');
  await p.locator('#message').fill('do not ignore the weekly backups');
  await p.locator('#chatForm button').click();
  if(!await p.locator('#content').innerText().then(t=>t.includes('weekly'))) throw Error('Ordinary ignore sentence froze backup memory');
  for(let m of ['Complete backups','yes','daily','yes','Actually backups are weekly']){
    await p.locator('#message').fill(m);
    await p.locator('#chatForm button').click();
  }
  if(!await p.locator('#content').innerText().then(t=>t.includes('weekly')&&t.includes('User-confirmed')&&t.includes('Conflict'))) throw Error('Memory/status failed');
  await p.screenshot({path:path.join(out,'security-chat.png'),fullPage:true});
  await p.reload();
  await p.getByRole('button',{name:'Enter workspace'}).click();
  await p.locator('[data-view="chat"]').click();
  if(!await p.locator('#content').innerText().then(t=>t.includes('weekly'))) throw Error('Persistence failed');
  await p.locator('[data-source="mfa-policy-v1"]').first().click();
  const src=await p.locator('#sourceBody').innerText();
  if(!src.includes('Digest matches')) throw Error('Hash failed');
  if(!/integrity/i.test(src)&&!/truth/i.test(src)) throw Error('Source inspector must keep integrity ≠ truth');
  await p.locator('#source button').click();
  await p.locator('#resolve').click();
  await p.locator('[data-view="questions"]').click();
  let d=p.waitForEvent('download');
  await p.locator('#export').click();
  const exportPath=path.join(out,'security-export.json');
  await (await d).saveAs(exportPath);
  const exported=JSON.parse(fs.readFileSync(exportPath,'utf8'));
  const statuses=(exported.questions||[]).map(q=>q.status);
  if(!statuses.includes('unknown')&&!(exported.statuses&&exported.statuses.unknown>0)) throw Error('Export hid unknowns');
  await p.setViewportSize({width:390,height:844});
  await p.locator('[data-view="overview"]').click();
  await p.screenshot({path:path.join(out,'security-mobile.png'),fullPage:true});
  if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)) throw Error('Mobile overflow');
  if(errors.length) throw Error(errors.join(';'));
  console.log('PASS browser: chat, correction, reload, source hash, resolution, export, mobile, WebGL');
  await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
